language: cpp

env:
 - release
compiler:
  - gcc
  - clang

before_install:
  - echo $LANG
  - echo $LC_ALL
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - echo $CXX
  - echo `g++ --version`
  - if [ "$CXX" = "clang++" ]; then sudo apt-get install -qq libstdc++-4.9-dev; fi
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.9; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.9"; fi
  - sudo apt-get install uuid-dev
  - git clone --depth 1 "git://github.com/jedisct1/libsodium.git -b 0.4.5" libsodium
  - cd libsodium
  - ./autogen.sh
  - ./configure
  - make
  - sudo make install
  -  cd ..
  - git clone https://github.com/zeromq/zeromq4-1 zeromq4-1
  - cd zeromq4-1
  - ./autogen.sh
  - ./configure
  - make
  - sudo make install
  - sudo /sbin/ldconfig
  - cd ..
 
before_script:
 - mkdir build
 - cd build
 - cmake -DCMAKE_BUILD_TYPE=Release ..


script:
- make install

branches:
  only:
    - master


notifications:
  email: false
  irc:
    channels:
      - "chat.freenode.net#lightq"
    template:
      - "%{repository}/%{branch} (%{commit} - %{author}): %{build_url}: %{message}"
  webhooks:
    on_success: change
    on_failure: always
    on_start: always



os:
  - linux
  - osx

